// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzpOEElsfizj7KwK_qdcElT6HVyv-5_1w',
    appId: '1:146585574223:web:18736397a7adc6537b833a',
    messagingSenderId: '146585574223',
    projectId: 'todo-f6413',
    authDomain: 'todo-f6413.firebaseapp.com',
    storageBucket: 'todo-f6413.appspot.com',
    measurementId: 'G-X2Y78H93ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK2pog_uwmcZkCvPpQLHxwzTczpBUHS_8',
    appId: '1:146585574223:android:ae3829c209a428987b833a',
    messagingSenderId: '146585574223',
    projectId: 'todo-f6413',
    storageBucket: 'todo-f6413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA10Sxp9PXJcyjvRT5sxRYRau1IshxwOs',
    appId: '1:146585574223:ios:4ed58a0b09c29cb27b833a',
    messagingSenderId: '146585574223',
    projectId: 'todo-f6413',
    storageBucket: 'todo-f6413.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA10Sxp9PXJcyjvRT5sxRYRau1IshxwOs',
    appId: '1:146585574223:ios:ddc86116c2d0bd157b833a',
    messagingSenderId: '146585574223',
    projectId: 'todo-f6413',
    storageBucket: 'todo-f6413.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
